---

dist: focal
language: minimal

env:
  - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3

# Install ansible
addons:
  apt:
    packages:
      - ansible
      - ansible-lint

install:
  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ansible-lint
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"
  - ls -lh /etc/apt/sources.list.d/
  - cat /etc/apt/sources.list.d/pgdg.list
  - cat /etc/apt/sources.list.d/repo_mongodb_org_apt_ubuntu.list
  - mongod --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
