---

- name: Add apt key
  ansible.builtin.get_url:
    url: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
    dest: /etc/apt/trusted.gpg.d/server-{{ mongodb_version }}.asc
    mode: '0644'
  become: true

- name: Set apt component for ubuntu
  ansible.builtin.set_fact:
    mongodb_apt_component: multiverse
  when: ansible_distribution == 'Ubuntu'

- name: Add apt-repo
  ansible.builtin.apt_repository:
    repo: deb http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ mongodb_apt_suite }} {{ mongodb_apt_component }}
    state: present
  become: true

- name: Install mongodb
  ansible.builtin.apt:
    name:
      - mongodb-org-server
      - mongodb-org-tools
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
